# Generated by Django 4.2.4 on 2023-09-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kitty',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'kitty',
                'verbose_name_plural': 'kitty',
                'db_table': 'kitty',
                'ordering': ['id'],
            },
        ),
    ]
